### ISSUE TITLE
Installer.sh missing

### ISSUE THREAD

**Issue by secme** [haroonawanofficial/Dmap#1]
Found it in a fork. It was broken anyway using full incorrect paths and only installed VASL

Below will work, run with sudo

cd Dmap
chmod u+x *
chmod u+x ./
sudo ln -fsT ./Vasl/vasl.py /usr/bin/vasl
chmod u+x ./Vasl/vasl.py
chmod u+x ./Vasl/cleaner.sh
chmod u+x /usr/bin/vasl
cpan Mojolicious
cpan Data::Validate::Domain

**Comment by haroonawanofficial** [comment]
Thanks.
